package store

var adminSchemaStatements = []string{
	`CREATE TABLE IF NOT EXISTS admin_users (
		id TEXT PRIMARY KEY,
		username TEXT NOT NULL UNIQUE COLLATE NOCASE,
		display_name TEXT NOT NULL,
		role TEXT NOT NULL CHECK(role IN ('owner', 'admin')),
		password_hash TEXT NOT NULL,
		enabled INTEGER NOT NULL CHECK(enabled IN (0, 1)),
		password_changed_at DATETIME NOT NULL,
		last_login_at DATETIME,
		totp_secret_encrypted BLOB,
		totp_enabled_at DATETIME,
		created_at DATETIME NOT NULL,
		updated_at DATETIME NOT NULL
	)`,
	`CREATE INDEX IF NOT EXISTS idx_admin_users_enabled_role ON admin_users(enabled, role)`,
	`CREATE TABLE IF NOT EXISTS admin_sessions (
		id TEXT PRIMARY KEY,
		user_id TEXT NOT NULL,
		token_hash BLOB NOT NULL UNIQUE,
		token_prefix TEXT NOT NULL,
		created_at DATETIME NOT NULL,
		last_activity_at DATETIME NOT NULL,
		idle_expires_at DATETIME NOT NULL,
		absolute_expires_at DATETIME NOT NULL,
		reauthenticated_until DATETIME,
		ip_address TEXT NOT NULL,
		user_agent TEXT NOT NULL,
		revoked_at DATETIME,
		FOREIGN KEY(user_id) REFERENCES admin_users(id) ON DELETE CASCADE
	)`,
	`CREATE INDEX IF NOT EXISTS idx_admin_sessions_user_active ON admin_sessions(user_id, revoked_at)`,
	`CREATE INDEX IF NOT EXISTS idx_admin_sessions_expiry ON admin_sessions(idle_expires_at, absolute_expires_at)`,
	`CREATE TABLE IF NOT EXISTS admin_audit_events (
		id TEXT PRIMARY KEY,
		request_id TEXT NOT NULL,
		actor_id TEXT,
		actor_username TEXT NOT NULL,
		action TEXT NOT NULL,
		resource_type TEXT NOT NULL,
		resource_id TEXT NOT NULL,
		outcome TEXT NOT NULL CHECK(outcome IN ('success', 'failure')),
		detail_json TEXT NOT NULL,
		ip_address TEXT NOT NULL,
		user_agent TEXT NOT NULL,
		session_prefix TEXT NOT NULL,
		created_at DATETIME NOT NULL
	)`,
	`CREATE INDEX IF NOT EXISTS idx_admin_audit_created ON admin_audit_events(created_at DESC)`,
	`CREATE INDEX IF NOT EXISTS idx_admin_audit_action ON admin_audit_events(action, created_at DESC)`,
	`CREATE INDEX IF NOT EXISTS idx_admin_audit_actor ON admin_audit_events(actor_id, created_at DESC)`,
	`CREATE TABLE IF NOT EXISTS admin_backups (
		id TEXT PRIMARY KEY,
		filename TEXT NOT NULL UNIQUE,
		source TEXT NOT NULL CHECK(source IN ('generated', 'uploaded')),
		state TEXT NOT NULL CHECK(state IN ('running', 'ready', 'failed', 'validated', 'staged')),
		created_at DATETIME NOT NULL,
		completed_at DATETIME,
		snapshot_cutoff DATETIME,
		size_bytes INTEGER NOT NULL DEFAULT 0,
		sqlite_bytes INTEGER NOT NULL DEFAULT 0,
		metrics_bytes INTEGER NOT NULL DEFAULT 0,
		metric_rows INTEGER NOT NULL DEFAULT 0,
		error_message TEXT NOT NULL DEFAULT ''
	)`,
	`CREATE INDEX IF NOT EXISTS idx_admin_backups_created ON admin_backups(created_at DESC)`,
}
